# Generated by Django 4.0.6 on 2022-09-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
