# Generated by Django 4.1 on 2022-08-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0003_userpost_alt_caption_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
