# Generated by Django 4.1 on 2022-08-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0004_alter_userpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
