# Generated by Django 4.0.6 on 2022-10-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0005_remove_userprofile_following_userprofile_following_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserFollowing',
        ),
    ]
