# Generated by Django 4.1 on 2022-08-24 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0005_userpost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='media_path',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='video',
        ),
        migrations.CreateModel(
            name='UserVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postitApp.userpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postitApp.userpost')),
            ],
        ),
    ]
