# Generated by Django 4.0.6 on 2022-11-06 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0009_alter_userpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='userDogPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postitApp.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='user_owns',
            field=models.ManyToManyField(related_name='owns', through='postitApp.userDogPreference', to=settings.AUTH_USER_MODEL),
        ),
    ]
