# Generated by Django 4.0.6 on 2022-11-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postitApp', '0010_dog_userdogpreference_dog_user_owns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
